const express = require('express')
const cors = require('cors')
const app = express()
const router = require('./route')
app.use(cors())
app.use(express.json())
app.use(express.urlencoded({ extended: false }))
app.use('/', router)
app.listen(3000, () => console.log('server listening on port 3000'))
